In [ ]:
list = [13,21,12]
for a in list:
  if a<20 and a%3 ==0:
    print(a)

12


# 1주차 pytorch_basic 

In [2]:
import numpy as np
import torch

In [ ]:
# 1D Array with pyTorch
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t)

print(t.dim()) #rank
print(t.shape)
print(t.size())

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [ ]:
# 2D Array with pyTorch
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                      [7, 8, 9],
                       [7, 8, 9]])
print(t)
print(t.dim()) #rank
print(t.shape)
print(t.size())


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [7., 8., 9.]])
2
torch.Size([4, 3])
torch.Size([4, 3])


# Broadcasting

In [ ]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# vector +scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

# 2 *1 vector + 1*2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3] , [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# sum
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum)
print(t.sum(dim = 0))
print(t.sum(dim = 1))

tensor([[1., 2.],
        [3., 4.]])
<built-in method sum of Tensor object at 0x7f40241cce30>
tensor([4., 6.])
tensor([3., 7.])


In [ ]:
# max
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())

print(t.max(dim = 0))
print('max', t.max(dim=0)[0])
print('argmax' , t.max(dim = 0)[1])

print(t.max(dim=1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
max tensor([3., 4.])
argmax tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [5]:
# view(reshape)

t= np.array([[[0, 1, 2],
              [3, 4, 5]],
             [[6, 7 ,8],
              [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [7]:
# squeeze 
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])


In [10]:
# unsqueeze
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

print(ft.view(1, -1))
print(ft.view(1, -1).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


# Type Casting


In [11]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)

print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# Concatenate

In [13]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y] ,dim = 0))
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking

In [14]:
x = torch.FloatTensor([1, 2])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 2.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [2., 5., 6.]])


# Ones and Zeros

In [15]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
