# 1주차 pytorch_basic 

In [1]:
import numpy as np
import torch

In [3]:
# 1D Array with pyTorch
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t)

print(t.dim()) #rank
print(t.shape)
print(t.size())

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [8]:
# 2D Array with pyTorch
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                      [7, 8, 9],
                       [7, 8, 9]])
print(t)
print(t.dim()) #rank
print(t.shape)
print(t.size())


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [7., 8., 9.]])
2
torch.Size([4, 3])
torch.Size([4, 3])


# Broadcasting

In [10]:
# same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# vector +scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

# 2 *1 vector + 1*2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3] , [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [11]:
# sum
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum)
print(t.sum(dim = 0))
print(t.sum(dim = 1))

tensor([[1., 2.],
        [3., 4.]])
<built-in method sum of Tensor object at 0x7f40241cce30>
tensor([4., 6.])
tensor([3., 7.])


In [13]:
# max
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())

print(t.max(dim = 0))
print('max', t.max(dim=0)[0])
print('argmax' , t.max(dim = 0)[1])

print(t.max(dim=1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
max tensor([3., 4.])
argmax tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
